changed streaming domain; new install helper for new product launch

diff --git a/install_scripts/python b/install_scripts/python
--- a/install_scripts/python
+++ b/install_scripts/python
@@ -79,15 +79,84 @@ function check_for_isstreamer {
 		pip install ISStreamer
 	else
 		echo "ISStreamer found, updating..."
-		
+
 		pip install --upgrade ISStreamer
 	fi
+
+	isstreamer_version=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('ISStreamer').version)")
+
+	echo "Found ISStreamer: $isstreamer_version"
+	isstreamer_version_array=(${isstreamer_version//" "/ })
+	isstreamer_version_num=${isstreamer_version_array[0]}
+	isstreamer_version_num_array=(${isstreamer_version_num//./ })
+	isstreamer_major_version=${isstreamer_version_num_array[0]}
+	isstreamer_minor=${isstreamer_version_num_array[1]}
+	isstreamer_minor_version_array=(${isstreamer_minor//"rc"/ })
+	isstreamer_minor_version=${isstreamer_minor_version_array[0]}
+
+	echo "isstreamer major version: $isstreamer_major_version"
+	echo "isstreamer minor version: $isstreamer_minor_version"
 }
 
 function download_script {
-	echo -n "Enter www.initialstate.com user email: "
-	read username < /dev/tty 
-	echo -n "Enter www.initialstate.com password [input hidden]: "
+	echo "Please select which Initial State app you're using: "
+	echo "1) app.initialstate.com"
+	echo "2) [NEW!] iot.app.initialstate.com"
+	echo -n "Enter choice 1 or 2: "
+	read app_version < /dev/tty
+
+	if [ "$app_version" = "1" ]; then
+		echo -n "Enter app.initialstate.com user email: "
+		read username < /dev/tty
+		echo -n "Enter app.initialstate.com password [input hidden]: "
+		read -s password < /dev/tty
+		echo ""
+
+		if [ -z "$example_location" ]; then
+			example_location="./is_example.py"
+		fi
+
+		python_example=$(curl -X POST "https://api.initialstate.com/api/v1/python/example" -H "X-USER: $username" -H "X-SEC: $password" -H "Accept-Content: text/plain" -m 30 -d "" -s)
+
+		if [ "$python_example" = "INVALID_CREDENTIALS" ]; then
+			echo "invalid credentials, let's try that again!"
+			download_script
+		else
+			echo "$python_example" | sudo -u $SUDO_USER tee "$example_location" > /dev/null
+		fi
+	else
+		echo -n "Enter iot.app.initialstate.com user email: "
+		read username < /dev/tty
+		echo -n "Enter iot.app.initialstate.com password [input hidden]: "
+		read -s password < /dev/tty
+		echo ""
+
+		if [ -z "$example_location" ]; then
+			example_location="./is_example.py"
+		fi
+
+		python_example=$(curl -X POST "https://api.init.st/dev-auth/python/example" -H "X-USER: $username" -H "X-PASS: $password" -H "Accept-Content: text/plain" -m 30 -d "" -s)
+
+		if [ "$python_example" = "INVALID_CREDENTIALS" ]; then
+			echo "invalid credentials, let's try that again!"
+			download_script
+		elif [ "$python_example" = "NOT_CURRENT" ]; then
+			echo "your account hasn't been migrated, go to iot.app.initialstate.com to sign in or create a new account"
+			download_script
+		elif [ "$python_example" = "{\"message\":\"Missing Authentication Token\"}" ]; then
+			echo "there's currently an issue with this endpoint, try again later or email support@initialstate.com. Thanks!"
+			exit 1
+		else
+			echo "$python_example" | sudo -u $SUDO_USER tee "$example_location" > /dev/null
+		fi
+	fi
+
+}
+
+function download_script_old {
+	echo -n "Enter app.initialstate.com user email: "
+	read username < /dev/tty
+	echo -n "Enter app.initialstate.com password [input hidden]: "
 	read -s password < /dev/tty
 	echo ""
 
@@ -96,7 +165,7 @@ function download_script {
 	fi
 
 	python_example=$(curl -X POST "https://api.initialstate.com/api/v1/python/example" -H "X-USER: $username" -H "X-SEC: $password" -H "Accept-Content: text/plain" -m 30 -d "" -s)
-	
+
 	if [ "$python_example" = "INVALID_CREDENTIALS" ]; then
 		echo "invalid credentials, let's try that again!"
 		download_script
@@ -113,9 +182,13 @@ function setup_first_script {
 		echo "Where do you want to save the example? [default: ./is_example.py]: "
 		read example_location < /dev/tty
 
-		download_script
+		if [ "$isstreamer_major_version" -gt "0" ]; then
+			download_script
+		else
+			download_script_old
+		fi
 	fi
-	
+
 	echo "All done!"
 }
 
